### ISSUE TITLE
CP & Control Thresholds requirements for other actors

### ISSUE THREAD

**Issue by Dana-Johnson** [mjeffw/nordlond-bestiary-public#2]
When I create an actor and import a GCS sheet, there is no CP or Control Threshold information.  What do I need to do to make those part of the character.  After all, it is no fun to only have the Nordlond creatures grappling amongst themselves.  Also, no 'Import' button is showing on my Nordlond sheets like it shows in the readme.  Thank you

**Comment by mjeffw** [comment]
After importing a character sheet from GCS, click on the down arrow icon next to the "Resource Trackers" section title. Select "+ Add Resource Tracker at the end". When the tracker appears, click the pencil icon on the tracker header. Ensure that the "Resource Tracker Templates" dropdown menu in the resulting dialog is showing "Control Points", and then click the "Copy Template" button.

Can you attach a screen shot of your Nordlond sheet so I can see the missing "Import" button? Thanks.

**Comment by Dana-Johnson** [comment]
Here is the original sheet:
![Nordlond - No Import](https://user-images.githubusercontent.com/22640155/188330256-fe793c92-d911-49f1-99ea-1a7d8abd5399.jpg)

I followed your instructions to add the Control Points tracker and it seems to work great and displays grapple status on the GCS sheet:
![Nordlond - GCS - No Import](https://user-images.githubusercontent.com/22640155/188330327-59da3df3-d280-4160-b2b1-62744663498a.jpg)

On the NordLond sheet, the Control Threshold doesn't seem to change as you can see it is displaying the red 20.  Also, still no import:
![Nordlond - CP - No Import](https://user-images.githubusercontent.com/22640155/188330372-34558c4f-447a-42f1-90b0-b7d94fb867df.jpg)

**Comment by mjeffw** [comment]
Okay. Now I know what you are trying to do. The Nordlond sheet isn't currently supported for characters not imported out of the Nordlond Bestiary. If you want to use this sheet for any actor, open a new issue for just that request. That way I won't forget it!

**Comment by Dana-Johnson** [comment]
Ah, well that would explain why the import isn't there anymore.  Will do!
