### ISSUE TITLE
Nordlond Beast sheet skill buttons broken

### ISSUE THREAD

**Issue by polkageist455** [mjeffw/nordlond-bestiary-public#5]
Foundry version 10 build 291
GURPS 4e Game Aid 0.15.17

The nordlond beast sheet attack links no longer work, when they are clicked (for ex. "Bite (14)" on a bear) I get an error message: 
"No melee attack named 'Bite ()' found on Bear, Brown"

This is true for ranged attacks as well, which have the same error message that indicates they're looking for a melee attack.
Clickable skills, spells, advantages, attributes work as expected, clickable defenses work as expected. It looks like it's only the clickable skills in the "Attacks" section.

This error does not occur when using other sheet styles, such as Tabbed, Combat, or the default sheet.

**Comment by mjeffw** [comment]
Thanks for the error report! I'll get to work on that right away.

**Comment by mjeffw** [comment]
@polkageist455 This issue should be fixed with v1.1.3. Please check it out and let me if this solved your problem. Thanks again for the error report!
