### ISSUE TITLE
Can't Upgrade to Version 1.4.0

### ISSUE THREAD

**Issue by Verny56** [mjeffw/nordlond-bestiary-public#8]
When I try to upgrade the bestiary, The Forge tells me that I can't downgrade, and that I have a newer version.I have version 1.1.3 installed. How can I fix this?
![Error message Screenshot 2024-04-11 184211](https://github.com/mjeffw/nordlond-bestiary-public/assets/74631699/dfcbf4e6-61af-48ce-805c-5ab211ba7bfa)

**Comment by mjeffw** [comment]
This was caused by something stupid I did on one of the versions between 1.1.3 and 1.4.0. You can manually fix this by deleting the module and downloading 1.4.0 (instead of doing an upgrade).
